"""add TimeEntry table

Revision ID: 67ead78fc499
Revises: 70ea25d10abe
Create Date: 2023-09-21 13:59:32.124692

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ead78fc499'
down_revision = '70ea25d10abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('time_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=64), nullable=True),
    sa.Column('project', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=True),
    sa.Column('modifier', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_time_entry_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_project'), ['project'], unique=False)
        batch_op.create_index(batch_op.f('ix_time_entry_start_time'), ['start_time'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_time_entry_start_time'))
        batch_op.drop_index(batch_op.f('ix_time_entry_project'))
        batch_op.drop_index(batch_op.f('ix_time_entry_description'))
        batch_op.drop_index(batch_op.f('ix_time_entry_category'))

    op.drop_table('time_entry')
    # ### end Alembic commands ###
